Set-Service -StartupType Disabled -Name "DiagTrack"
Set-Service -StartupType Disabled -Name "DusmSvc"
Set-Service -StartupType Disabled -Name "LanmanWorkstation"
Set-Service -StartupType Disabled -Name "WSearch"
Set-Service -StartupType Disabled -Name "WpnService"
Set-Service -StartupType Disabled -Name "LicenseManager"
Set-Service -StartupType Disabled -Name "EventLog"
Set-Service -StartupType Disabled -Name "TokenBroker"
Set-Service -StartupType Disabled -Name "UsoSvc"
Set-Service -StartupType Disabled -Name "TabletInputService"
Set-Service -StartupType Disabled -Name "DPS"
Set-Service -StartupType Disabled -Name "iphlpsvc"
Set-Service -StartupType Disabled -Name "NcbService"
Set-Service -StartupType Disabled -Name "Spooler"
Set-Service -StartupType Disabled -Name "PcaSvc"
Set-Service -StartupType Disabled -Name "LanmanServer"
Set-Service -StartupType Disabled -Name "SysMain"
Set-Service -StartupType Disabled -Name "lmhosts"
Set-Service -StartupType Disabled -Name "Themes"
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "Shell" -Value "C:\Program Files (x86)\Overwatch\_retail_\Overwatch.exe"
shutdown /r /t 0